---
title: "methylation at siRNA loci"
author: "Chenxin Li"
date: "12/29/2020"
output:
  html_notebook:
    number_sections: yes
    toc: yes
    toc_float: yes
  html_document:
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(dplyr)
library(tidyr)
library(readr)
library(readxl)
library(emmeans) 
library(stringr)
library(RColorBrewer)
library(svglite) 
```

# load data 

```{r message=F, warning = F}
egg_meth_list <- list.files(path = "C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/CLVS_zygote_GR_revision/full_MTRs_zes_2021_10_13/egg_data/", 
                        pattern = "*.mtr", full.names = T) 

egg_meth_data <- sapply(egg_meth_list, read_delim, simplify = FALSE, 
                       delim = "\t", col_names = F, escape_double = F, trim_ws = T) %>% 
  bind_rows(.id = "id")

head(egg_meth_data) 
```
```{r}
egg_meth_data %>% 
  group_by(id) %>% 
  count()
```
 

# keying data 

each locus must have 3 or more reads to be considered in the analyses 
```{r}
set.seed(666)
egg_meth_data_nice <- egg_meth_data %>%
  #group_by(id) %>% 
  #sample_n(10000) %>% 
  ungroup() %>% 
  filter(X7 >= 3) %>% 
   mutate(sample_ID = case_when(
    str_detect(id, "egg100_1") ~ "egg Li et al.1", 
    str_detect(id, "egg100_2") ~ "egg Li et al.2",
    str_detect(id, "_EC.") ~ "egg Park et al",
    str_detect(id, "SRR10915149") ~ "egg Zhou et al.1",
    str_detect(id, "SRR10915150") ~ "egg Zhou et al.2"
  )) %>% 
  filter(is.na(sample_ID) == F) %>% 
  mutate(locus = case_when(
    str_detect(id, "egg_loci") ~ "egg siRNA loci", #1
    str_detect(id, "seedling_loci") ~ "seedling siRNA loci", #2
    str_detect(id, "embryo_loci") ~ "embryo siRNA loci", #3 
    str_detect(id, "zygote-egg_complement_loci.") ~ "Z loci - E loci", #4
    str_detect(id, "sperm_loci") &
      str_detect(id, "endo") == F ~ "sperm siRNA loci", #5 
    str_detect(id, "egg-zygote_complement_loci.") ~ "E loci - Z loci", #6 
    str_detect(id, "zygote_loci.") ~ "zygote siRNA loci" #7
  )) %>% 
  filter(is.na(locus) == F) %>% 
  mutate(context = case_when(
    str_detect(id, "gz.CG.") ~ "mCG", 
    str_detect(id, "gz.CHG.") ~ "mCHG", 
    str_detect(id, "gz.CHH.") ~ "mCHH"
  ))  

head(egg_meth_data_nice)
```
 
 

# stats
```{r}
egg_meth_data_nice %>% 
  group_by(locus, context) %>% 
  count()
```

```{r}
egg_meth_data_nice %>% 
  group_by(locus, context, sample_ID) %>% 
  count
```


## summary stats - quantiles 
```{r}
egg_meth_data_ss <- egg_meth_data_nice %>% 
  filter(is.na(X4) == F) %>% 
  group_by(sample_ID, locus, context) %>% 
  summarise(
    NN = n(),
    median = median(X4),
    mean = mean(X4),
    Q3 = quantile(X4, 0.75),
    Q1 = quantile(X4, 0.25),
    UL = quantile(X4, 0.975),
    LL = quantile(X4, 0.025)
  ) %>% 
  ungroup() %>% 
  mutate(paper = case_when(
    str_detect(sample_ID, "Zhou") ~ "Zhou et al.",
    str_detect(sample_ID, "Park") ~ "Park et al.",
    str_detect(sample_ID, "Li et al") ~ "Li et al.",
  ))

egg_meth_data_ss
```
```{r}
egg_meth_data_ss %>% 
  filter(context == "mCHH") %>% 
  arrange(mean)

write_excel_csv(egg_meth_data_ss, "egg_meth_data_ss.csv")
```
 


## linear models
```{r}
logit <- function(p){log(
  p / (1-p)
)}

logistic <- function(x){
  1/(1 + exp(-x))
}
```

```{r}
model_egg_meth <- glm(X4 ~ sample_ID* context * locus, data = egg_meth_data_nice %>% 
                        group_by(id) %>% 
                        sample_n(10000), 
                     family = quasibinomial(link = "logit")) 

anova(model_egg_meth, test = "LRT")
```

```{r}
est_egg_meth1 <- emmeans(model_egg_meth, pairwise ~ sample_ID | locus | context)
est_egg_meth2 <- emmeans(model_egg_meth, pairwise ~ locus | sample_ID | context)
```

```{r}
egg_meth_results <- multcomp::cld(est_egg_meth1$emmeans, Letters = letters) %>% 
  as.data.frame() %>% 
  mutate(grouping = str_remove_all(.group, " ")) 

egg_meth_results %>% 
  filter(context == "mCHH") %>% 
  select(sample_ID, locus, context, grouping)
```

```{r}
est_egg_meth1$contrasts %>% 
  as.data.frame() %>% 
  filter(context == "mCHH") %>% 
  select(contrast, p.value)
```


# plot - ~ sample | locus 
## CHH 
```{r}
egg_meth_data_ss %>% 
  filter(context == "mCHH") %>%
  inner_join(egg_meth_results, by = c("sample_ID", "locus", "context")) %>% 
  mutate(locus2 = case_when(
    str_detect(locus, "embryo siRNA loci") ~ "*embryo siRNA loci",
    T ~ locus
  )) %>% 
  mutate(locus = reorder(locus2, mean)) %>% 
  ggplot(aes(x = sample_ID, y = Q3)) +
  facet_wrap(~locus, nrow = 2, strip.position = "top") + 
  geom_crossbar(aes(ymin = Q1, ymax = Q3, y = median, fill = paper), width = 0.7, alpha = 0.8) +
  geom_segment(aes(x = sample_ID, xend = sample_ID,  y = Q3, yend = UL)) +
  geom_segment(aes(x = sample_ID, xend = sample_ID,  y = Q1, yend = LL)) +
  geom_errorbar(aes(ymin = UL, ymax = UL), width = 0.3, size = 1) +
  geom_errorbar(aes(ymin = LL, ymax = LL), width = 0.3, size = 1) +
  geom_text(aes(label = grouping, y = Q3), 
  hjust = -0.5, size = 4, fontface = "bold", vjust = -0.2) +
  scale_fill_manual(values = c("#541352", "#2f9aa0", "#ffcf20")) + 
  labs(x = NULL, 
       y = "mCHH in WT egg cell",
       fill = "methylome data") +
  theme_minimal() +
  theme(
    text = element_text(size = 14, face = "bold", colour = "black"),
    axis.text = element_text(colour = "black"), 
    axis.text.y = element_blank(),
    strip.placement = "outside",
    strip.text.y = element_text(hjust = 0.5, angle = 0, face = "bold"), 
    panel.spacing = unit(1.25, "lines"),
    axis.line = element_line(size = 1),
    legend.position = c(0.875, 0.25)
  ) +
  coord_flip()  

ggsave("egg_meth.svg", height = 4, width = 9)
ggsave("egg_meth.png", height = 4, width = 9)
```
 


## CHG 
```{r}
egg_meth_data_ss %>% 
  filter(context == "mCHG") %>%
  inner_join(egg_meth_results, by = c("sample_ID", "locus", "context")) %>% 
  mutate(locus2 = case_when(
    str_detect(locus, "embryo siRNA loci") ~ "*embryo siRNA loci",
    T ~ locus
  )) %>% 
  mutate(locus = reorder(locus2, mean)) %>% 
  ggplot(aes(x = sample_ID, y = Q3)) +
  facet_wrap(~locus, nrow = 2, strip.position = "top") + 
  geom_crossbar(aes(ymin = Q1, ymax = Q3, y = median, fill = paper), width = 0.7, alpha = 0.8) +
  geom_segment(aes(x = sample_ID, xend = sample_ID,  y = Q3, yend = UL)) +
  geom_segment(aes(x = sample_ID, xend = sample_ID,  y = Q1, yend = LL)) +
  geom_errorbar(aes(ymin = UL, ymax = UL), width = 0.3, size = 1) +
  geom_errorbar(aes(ymin = LL, ymax = LL), width = 0.3, size = 1) +
  geom_text(aes(label = grouping, y = Q1), 
  hjust = 1.3, size = 4, fontface = "bold", vjust = -0.2) +
  scale_fill_manual(values = c("#541352", "#2f9aa0", "#ffcf20")) + 
  labs(x = NULL, 
       y = "mCHG in WT egg cell",
       fill = "methylome data") +
  theme_minimal() +
  theme(
    text = element_text(size = 14, face = "bold", colour = "black"),
    axis.text = element_text(colour = "black"), 
    axis.text.y = element_blank(),
    strip.placement = "outside",
    strip.text.y = element_text(hjust = 0.5, angle = 0, face = "bold"), 
    panel.spacing = unit(1, "lines"),
    axis.line = element_line(size = 1),
    legend.position = c(0.875, 0.25)
  ) +
  coord_flip()  

ggsave("egg_meth_CHG.svg", height = 4, width = 9)
ggsave("egg_meth_CHG.png", height = 4, width = 9)
```

## GG
```{r}
egg_meth_data_ss %>% 
  filter(context == "mCG") %>%
  inner_join(egg_meth_results, by = c("sample_ID", "locus", "context")) %>% 
  mutate(locus2 = case_when(
    str_detect(locus, "embryo siRNA loci") ~ "*embryo siRNA loci",
    T ~ locus
  )) %>% 
  mutate(locus = reorder(locus2, mean)) %>% 
  ggplot(aes(x = sample_ID, y = Q3)) +
  facet_wrap(~locus, nrow = 2, strip.position = "top") + 
  geom_crossbar(aes(ymin = Q1, ymax = Q3, y = median, fill = paper), width = 0.7, alpha = 0.8) +
  geom_segment(aes(x = sample_ID, xend = sample_ID,  y = Q3, yend = UL)) +
  geom_segment(aes(x = sample_ID, xend = sample_ID,  y = Q1, yend = LL)) +
  geom_errorbar(aes(ymin = UL, ymax = UL), width = 0.3, size = 1) +
  geom_errorbar(aes(ymin = LL, ymax = LL), width = 0.3, size = 1) +
  geom_text(aes(label = grouping, y = Q1), 
  hjust = 1.3, size = 4, fontface = "bold", vjust = -0.2) +
  scale_fill_manual(values = c("#541352", "#2f9aa0", "#ffcf20")) + 
  labs(x = NULL, 
       y = "mCG in WT egg cell",
       fill = "methylome data") +
  theme_minimal() +
  theme(
    text = element_text(size = 14, face = "bold", colour = "black"),
    axis.text = element_text(colour = "black"), 
    axis.text.y = element_blank(),
    strip.placement = "outside",
    strip.text.y = element_text(hjust = 0.5, angle = 0, face = "bold"), 
    panel.spacing = unit(1, "lines"),
    axis.line = element_line(size = 1),
    legend.position = c(0.875, 0.25)
  ) +
  coord_flip()  


ggsave("egg_meth_CG.svg", height = 4, width = 9)
ggsave("egg_meth_CG.png", height = 4, width = 9)
```

# plot - ~ locus | sample 
pull out groupings 
```{r}
egg_meth_results2 <- multcomp::cld(est_egg_meth2$emmeans, Letters = letters) %>% 
  as.data.frame() %>% 
  mutate(grouping = str_remove_all(.group, " ")) 

egg_meth_results2 %>% 
  filter(context == "mCHH") %>% 
  select(sample_ID, locus, context, grouping)
```

## CHH
```{r}
egg_meth_data_ss %>% 
  filter(context == "mCHH") %>%
  inner_join(egg_meth_results2, by = c("sample_ID", "locus", "context")) %>% 
  mutate(locus2 = case_when(
    str_detect(locus, "embryo siRNA loci") ~ "*embryo siRNA loci",
    T ~ locus
  )) %>% 
  mutate(locus = reorder(locus2, mean)) %>% 
  ggplot(aes(x = locus, y = Q3)) +
  facet_wrap(~sample_ID, ncol = 2, strip.position = "top") + 
  geom_crossbar(aes(ymin = Q1, ymax = Q3, y = median, fill = locus), width = 0.7, alpha = 0.8) +
  geom_segment(aes(x = locus2, xend = locus2,  y = Q3, yend = UL)) +
  geom_segment(aes(x = locus2, xend = locus2,  y = Q1, yend = LL)) +
  geom_errorbar(aes(ymin = UL, ymax = UL), width = 0.3, size = 1) +
  geom_errorbar(aes(ymin = LL, ymax = LL), width = 0.3, size = 1) +
  geom_text(aes(label = grouping, y = Q3), 
  hjust = -0.5, size = 4, fontface = "bold", vjust = -0.2) +
  scale_fill_manual(values = c("tomato1", "coral4", "grey80",
                               "seagreen", "dodgerblue2", 
                               "pink3", "violetred4"),
                    limits = c("egg siRNA loci", "E loci - Z loci", "*embryo siRNA loci",
                               "seedling siRNA loci", "sperm siRNA loci",
                               "Z loci - E loci", "zygote siRNA loci")) + 
  labs(x = NULL, 
       y = "mCHH in WT egg cell",
       fill = NULL) +
  guides(fill = guide_legend(ncol = 2)) +
  theme_minimal() +
  theme(
    text = element_text(size = 14, face = "bold", colour = "black"),
    axis.text = element_text(colour = "black"), 
    axis.text.y = element_blank(),
    strip.placement = "outside",
    strip.text.y = element_text(hjust = 0.5, angle = 0, face = "bold"), 
    panel.spacing = unit(1, "lines"),
    axis.line = element_line(size = 1),
    legend.position = "top"
  ) +
  coord_flip()  

ggsave("egg_meth_CHH_by_sample.svg", height = 8, width = 5)
ggsave("egg_meth_CHH_by_sample.png", height = 8, width = 5)
```


