---
title: "50KB Coverage of 24-nt siRNA"
author: "Chenxin Li"
date: "9/13/2021"
output:  
  html_notebook:
    number_sections: yes
    toc: yes
    toc_float: yes
  html_document:
    toc: yes
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(dplyr)
library(tidyr)
library(readr)
library(readxl)
library(stringr)
library(RColorBrewer)
library(svglite)
library(ggdendro)
library(cowplot)
```

# load data
```{r message=F, warning=F}
library_list <-  list.files(path = "C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/CLVS13/50kb_siRNA_cov/", 
                         pattern = "*.cov", full.names = T)

long <- sapply(library_list, read_delim, delim = "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, simplify = F)  %>% 
  bind_rows(.id = "id") %>% 
  filter(str_detect(id, "OV9|zg"))

head(long)
```
 
```{r}
lengths_summary_sam <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/CLVS13/siRNA_length_counts_2021_04_16/lengths_summary.sam.txt", 
    "\t", escape_double = FALSE, trim_ws = TRUE) 

lengths_summary_sam_nice <- lengths_summary_sam %>% 
  filter(str_detect(X1, "OV9|zg")) %>% 
  mutate(sample_ID = str_sub(X1, end = 6)) %>% 
  select(-X1) %>% 
  mutate(sample_ID = case_when(
    str_detect(sample_ID, "zg") ~ str_sub(sample_ID, end = 4),
    T ~ sample_ID
  ))

head(lengths_summary_sam_nice)
```
 

 
# wrangle data  
```{r}
"C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/CLVS13/50kb_siRNA_cov/50KB." %>% 
  str_length()
```

```{r}
long2 <- long %>% 
  mutate(sample_ID = str_sub(id, start = 92, end = 92+5)) %>% 
  mutate(sample_ID = case_when(
    str_detect(sample_ID, "zg") ~ str_sub(sample_ID, end = 4),
    T ~ sample_ID
  )) %>% 
  inner_join(lengths_summary_sam_nice, by = "sample_ID") %>% 
  mutate(RPM = X9/`24` * 10^6)  

long2$RPM %>% summary()
```

```{r}
head(long2)
wide <- long2 %>% 
  select(X1, X4, X5, sample_ID, RPM) %>% 
  spread(sample_ID, RPM)

wide
```
 
# make heatmaps 
```{r}
cor_df_ov9 <- cor(wide[, 4:6]) %>% 
  as.data.frame() %>% 
  mutate(sample1 = row.names(.)) %>% 
  gather("sample2", cor, 1:3)

cor_df_ov9
```

```{r}
cor_df_ov9 %>% 
  ggplot(aes(x = sample1, y = sample2)) + 
  geom_tile(aes(fill = cor), alpha = 0.8) +
  geom_text(aes(label = cor %>% round(4)), size = 4, fontface = "bold") +
  #scale_fill_gradientn(colors = brewer.pal(9, "YlOrRd")[c(6:9)]) +
  scale_fill_viridis(begin = 0.5, end = 0.8, direction = -1, option = "A") +
  scale_x_discrete(label = c("rep1", "rep2", "rep3"))+
  scale_y_discrete(label = c("rep1", "rep2", "rep3"))+
  labs(x = NULL, 
       y = NULL) +
  theme_minimal() +
  theme(legend.position = "right") +
  theme(text = element_text(size= 14, face="bold")) +
  theme(axis.text.x=element_text(colour = "black", angle = 45, hjust = 1)) +
  theme(axis.text.y=element_text(colour = "black")) +
  theme(panel.grid = element_blank()) +
  coord_fixed()

ggsave("ov_cor.svg", height = 2.75, width = 3.75)
ggsave("ov_cor.png", height = 2.75, width = 3.75)
```
```{r}
cor_df_zg <- cor(wide[, 7:12]) %>% 
  as.data.frame() %>% 
  mutate(sample1 = row.names(.)) %>% 
  gather("sample2", cor, 1:6)

cor_df_zg
```


```{r}
cor_df_zg %>% 
  ggplot(aes(x = sample1, y = sample2)) + 
  geom_tile(aes(fill = cor)) +
  geom_text(aes(label = cor %>% round(4)), size = 4, fontface = "bold", alpha = 0.8) +
  #scale_fill_gradientn(colors = brewer.pal(9, "YlOrRd")[c(5:9)]) +
  scale_fill_viridis(begin = 0.5, end = 0.9, direction = -1, option = "A") +
  scale_x_discrete(label = c("rep1", "rep2", "rep3", "rep4", "rep5", "rep6"))+
  scale_y_discrete(label = c("rep1", "rep2", "rep3", "rep4", "rep5", "rep6"))+
  labs(x = NULL, 
       y = NULL) +
  theme_minimal() +
  theme(legend.position = "right") +
  theme(text = element_text(size= 18, face="bold")) +
  theme(axis.text.x=element_text(colour = "black", angle = 45, hjust = 1)) +
  theme(axis.text.y=element_text(colour = "black")) +
  theme(panel.grid = element_blank()) +
  coord_fixed()

ggsave("zg_cor.svg", height = 4.25, width = 5)
ggsave("zg_cor.png", height = 4.25, width = 5)
```

 

