---
title: "rice ChIP"
author: "Chenxin Li"
date: "8/6/2020"
output: html_notebook 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(ggplot2)
library(emmeans)
library(dplyr)
library(tidyr)
library(readr)
library(readxl)
library(purrr)
library(stringr)
library(RColorBrewer)
library(svglite)
library(cowplot)
library(ggdendro)
library(dynamicTreeCut)
```

```{r}
set.seed(6)
```


#data 
##read data 
```{r}
PE101_list <- list.files(path = "C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/CLVS12/ChIP_2020_08_05/PE101", 
                         pattern = "*.cov", full.names = T)

SE36_list <- list.files(path = "C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/CLVS12/ChIP_2020_08_05/SE36", 
                         pattern = "*.cov", full.names = T)

SE49_list <- list.files(path = "C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/CLVS12/ChIP_2020_08_05/SE49", 
                         pattern = "*.cov", full.names = T)


full_list <- c(PE101_list, SE36_list, SE49_list)
```

```{r}
subsample <- function(df){
  if(nrow(df) > 2000){
    sample_n(df, 2000)
  } else {
    df
  }
}

```

 
```{r}
ChIP_data <- sapply(full_list, read_delim, delim = "\t", escape_double = FALSE, col_names = F, 
    trim_ws = TRUE, simplify = F) %>% 
  sapply(FUN = rev, simplify = F) %>% 
  sapply(FUN = select, 1:4, simplify = F) %>%  
  sapply(FUN = subsample, simplify = F) %>% 
  bind_rows(.id = "id") 

head(ChIP_data)
```

##fix different column problem 
```{r}
C13 <- ChIP_data %>% 
  filter(str_detect(id, "genes|Gypsy|TIR")) %>% 
  select(id, X10, X11, X12, X13) %>% 
  rename(
    count = X10, 
    cov = X11,
    length = X12,
    frac = X13
  )

head(C13)
```


```{r}
C8 <- ChIP_data %>% 
  filter(str_detect(id, "loci")) %>%
  filter(str_detect(id, "specfic")== F) %>% 
  select(id, X5, X6, X7, X8) %>% 
  rename(
    count = X5, 
    cov = X6,
    length = X7,
    frac = X8
  )

head(C8)
```

 


##combine and normalize 
```{r}
PE101_cts_list <- list.files(path = "C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/CLVS12/chip_read_counts/PE101_read_counts",
                         pattern = "*.*", full.names = T) 

SE36_cts_list <- list.files(path = "C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/CLVS12/chip_read_counts/SE36_read_counts",
                         pattern = "*.*", full.names = T)

SE49_cts_list <- list.files(path = "C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/CLVS12/chip_read_counts/SE49_read_counts",
                         pattern = "*.*", full.names = T)

full_cts_list <- c(PE101_cts_list, SE36_cts_list, SE49_cts_list)

# total_reads <- read_excel("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/CLVS12/Rice_ChIP_total_reads.xlsx") 
# head(total_reads)
```

read_csv("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/CLVS12/chip_read_counts/PE101_read_counts/SRR1999337.1.o3077495", 
    col_names = FALSE)

```{r}
count_data <- sapply(full_cts_list, read_delim, escape_double = FALSE, col_names = F, delim = "\t", 
    trim_ws = TRUE, simplify = F) %>% 
  sapply(t, simplify = F) %>% 
  sapply(as.data.frame, simplify = F) %>% 
  bind_rows(.id = "id")
  

head(count_data)
```
```{r}
count_data_clean <- count_data %>% 
  mutate(sra = str_match(id, 
                         "SRR[:digit:][:digit:][:digit:][:digit:][:digit:][:digit:][:digit:]")) %>% 
  mutate(sra = case_when(
    is.na(sra) ~ str_match(id, 
                         "SRR[:digit:][:digit:][:digit:][:digit:][:digit:][:digit:]"),
    T ~ sra
  ))

count_data_clean
```


```{r}
ChIP_data_clean <- rbind(
  C8, C13
) %>% 
  mutate(sra = str_match(id, 
                         "SRR[:digit:][:digit:][:digit:][:digit:][:digit:][:digit:][:digit:]")) %>% 
  mutate(sra = case_when(
    is.na(sra) ~ str_match(id, 
                         "SRR[:digit:][:digit:][:digit:][:digit:][:digit:][:digit:]"),
    T ~ sra
  )) %>% 
  inner_join(count_data_clean %>% 
               select(-id), by = "sra") %>% 
  mutate(RPKM = count / V2 * 10^6 / length * 1000) 
 

head(ChIP_data_clean)
```



##keying the id
```{r}
chip_des <- read_excel("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/CLVS12/rice ChIP SRA table.xlsx", 
    col_names = c("sra", "type", "tissue", "tissue2","var", "publication", "format"))

chip_des <- chip_des %>% 
  filter(is.na(sra) == F) %>% 
  mutate(tissue2 = str_replace(tissue2, "_", "\n"))

head(chip_des)
```


```{r}
chip_keyed <- ChIP_data_clean %>% 
  mutate(category = case_when(
    str_detect(id, "TIR") ~ "TIR",
    str_detect(id, "Gypsy") ~ "Gypsy",
    str_detect(id, "genes") ~ "genes",
    str_detect(id, "ovary_siren") ~ "ovary siren loci",
    str_detect(id, "ovary_siRNA") ~ "ovary siRNA loci",
    str_detect(id, "seedling") ~ "seedling siRNA loci",
    str_detect(id, "sperm") ~ "sperm siRNA loci",
    str_detect(id, "zygote-spe") ~ "zygote specific loci"
  )) %>% 
  full_join(chip_des, by = "sra")  

chip_keyed %>% head(10)
```

 


#summary 
```{r}
chip_s_keyed<- chip_keyed %>%
  filter(is.na(RPKM) == F) %>% 
  group_by(id, category, type, tissue, tissue2) %>% 
  summarise(
            median = median(RPKM),
            Q3 = quantile(RPKM, 0.75),
            Q1 = quantile(RPKM, 0.25),
            UL = quantile(RPKM, 0.975),
            LL = quantile(RPKM, 0.025)
  ) %>% 
  ungroup()

head(chip_s_keyed) 
```

#PCA

```{r}
chip_s_keyed_wide <- chip_s_keyed %>% 
  filter(str_detect(type, "DNase|input|preimm") == F) %>% 
  mutate(class = paste(type, tissue2, sep = ":")) %>% 
  select(class, category, median) %>% 
  spread(category, median) %>% 
  as.data.frame()

rownames(chip_s_keyed_wide) <- chip_s_keyed_wide$class
head(chip_s_keyed_wide)
```
```{r}
pc <- prcomp(t(log10((chip_s_keyed_wide[, -1] + 1))))
#pc <- prcomp(t(chip_s_keyed_wide[, -1]))
pc_importance <- as.data.frame(t(summary(pc)$importance))
pc_importance
```

```{r}
pc$x %>% 
  as.data.frame() %>% 
  mutate(category = row.names(.)) %>%
  ggplot(aes(x = PC1, y = PC2)) +
  geom_vline(xintercept = 0, linetype = 4) +
  geom_hline(yintercept = 0, linetype = 4) +
  geom_point(aes(color = category), size = 3, alpha = 0.8)  +
  scale_color_manual(values = c("black", "orange2", "grey70",
                               "orangered3", "orangered1", "seagreen", "dodgerblue2", "violetred2"), 
                    limits = c("genes", "TIR", "Gypsy", 
                               "ovary siren loci", "ovary siRNA loci", "seedling siRNA loci", "sperm siRNA loci", 
                               "zygote specific loci")) +
  labs(x = paste("PC1 (", pc_importance[1, 2] %>% signif(3)*100, "% of Variance)", sep = ""), 
       y = paste("PC2 (", pc_importance[2, 2] %>% signif(3)*100, "% of Variance)", "  ", sep = ""),
       fill = NULL,
       color = NULL) +  
  guides(fill = F) +
  theme_bw() + 
  theme(text = element_text(size= 18, face="bold")) +
  theme(axis.text.x=element_text(colour = "black")) +
  theme(axis.text.y=element_text(colour = "black")) 


ggsave("PCA_chip.svg", width = 8, height = 5)
ggsave("PCA_chip.png", width = 8, height = 5)
```

```{r}
b <- pc$rotation %>% 
  as.data.frame() %>% 
  mutate(class = row.names(.)) %>% 
  separate(class, c("type", "tissue", sep = "\n"), remove = F) %>% 
  ggplot(aes(x = PC1, y = PC2)) +
  geom_segment(aes(x = 0, xend = PC1, y = 0, yend = PC2)) +
  geom_label(aes(label = type), nudge_x = 0.01, nudge_y = -0.01) +
  scale_x_continuous(limits = c(-0.45, 0.4)) +
  scale_y_continuous(limits = c(-0.6, 0.6)) +
  labs(x = paste("PC1 (", pc_importance[1, 2] %>% signif(3)*100, "% of Variance)", sep = ""), 
       y = paste("PC2 (", pc_importance[2, 2] %>% signif(3)*100, "% of Variance)", "  ", sep = ""),
       fill = NULL,
       color = NULL) +
  theme_bw() +
  theme(text = element_text(size= 18, face="bold")) +
  theme(axis.text.x=element_text(colour = "black")) +
  theme(axis.text.y=element_text(colour = "black")) 
b

ggsave("chip_pca_loading.svg", width = 5, height = 5)
ggsave("chip_pca_loading.png", width = 5, height = 5)
```
 



#tree
```{r}
all.dist <- dist(chip_s_keyed_wide[,-1] %>% t(), method = "e")
all.hc <- hclust(all.dist, method = "complete") 
plot(all.hc)
```

```{r}
dend_data <- dendro_data(all.hc, type = "rectangle")
tip <- dend_data$labels  

tip
```
```{r}
left <- tip %>% 
  ggplot(aes(x = x, y = -y)) +
  geom_segment(data = dend_data$segments, aes(x = x, y = -y, xend = xend, yend = -yend), 
               size = 2, lineend = "round", alpha = 0.8) +
  geom_point(aes(color = label), size = 3, alpha = 0.8) +
  geom_text(aes(label = label), size = 5, hjust = -0.2,
            fontface = "bold") +
  scale_x_continuous(labels = NULL) +
  scale_y_continuous(limits = c(-18, 10), labels = NULL) + 
  scale_color_manual(values = c("black", "orange2", "grey70",
                               "orangered3", "orangered1", "seagreen", "dodgerblue2"), 
                    limits = c("genes", "TIR", "Gypsy", 
                               "ovary siren loci", "ovary siRNA loci", "seedling siRNA loci", "sperm siRNA loci")) +
  labs(x = NULL,
       y = NULL,
       fill = NULL) +
  theme_minimal() +
  theme(legend.position = "none") +
  theme(text = element_text(size= 18, face="bold")) +
  theme(axis.text.x=element_text(colour = "black")) +
  theme(axis.text.y=element_text(colour = "black")) +
  theme(panel.grid = element_blank()) +
  coord_flip()

left
ggsave("dendro_chip.svg", width = 8, height = 5)
ggsave("dendro_chip.png", width = 8, height = 5)
```


 
```{r}
c <- tip %>% 
  ggplot(aes(x = x, y = -y)) +
  geom_segment(data = dend_data$segments, aes(x = x, y = -y, xend = xend, yend = -yend), 
               size = 2, lineend = "round", alpha = 0.8) +
  geom_point(aes(color = label), size = 3, alpha = 0.8) +
  scale_x_continuous(labels = NULL) +
  scale_y_continuous(limits = c(-18, 5), labels = NULL) + 
  scale_color_manual(values = c("black", "orange2", "grey70",
                               "orangered3", "orangered1", "seagreen", "dodgerblue2"), 
                    limits = c("genes", "TIR", "Gypsy", 
                               "ovary siren loci", "ovary siRNA loci", "seedling siRNA loci", "sperm siRNA loci")) +
  labs(x = NULL,
       y = NULL,
       fill = NULL) +
  theme_minimal() +
  theme(legend.position = "none") +
  theme(text = element_text(size= 18, face="bold")) +
  theme(axis.text.x=element_text(colour = "black")) +
  theme(axis.text.y=element_text(colour = "black")) +
  theme(panel.grid = element_blank()) +
  coord_flip()

c

ggsave("dendro_chip2.svg", height = 5, width = 5)
ggsave("dendro_chip2.png", height = 5, width = 5)
```
#cowplot
```{r}
a <- pc$x %>% 
  as.data.frame() %>% 
  mutate(category = row.names(.)) %>%
  ggplot(aes(x = PC1, y = PC2)) +
  geom_vline(xintercept = 0, linetype = 4) +
  geom_hline(yintercept = 0, linetype = 4) +
  geom_point(aes(color = category), size = 3, alpha = 0.8)  +
  scale_color_manual(values = c("black", "orange2", "grey70",
                               "orangered3", "orangered1", "seagreen", "dodgerblue2", "violetred2"), 
                    limits = c("genes", "TIR", "Gypsy", 
                               "ovary siren loci", "ovary siRNA loci", "seedling siRNA loci", "sperm siRNA loci", 
                               "zygote specific loci")) +
  labs(x = paste("PC1 (", pc_importance[1, 2] %>% signif(3)*100, "% of Variance)", sep = ""), 
       y = paste("PC2 (", pc_importance[2, 2] %>% signif(3)*100, "% of Variance)", "  ", sep = ""),
       fill = NULL,
       color = NULL) +  
  guides(fill = F) +
  theme_bw() +
  theme(legend.position = "none") +
  theme(text = element_text(size= 18, face="bold")) +
  theme(axis.text.x=element_text(colour = "black")) +
  theme(axis.text.y=element_text(colour = "black")) 
```


```{r}
legend.source <- get_legend(
  pc$x %>% 
  as.data.frame() %>% 
  mutate(category = row.names(.)) %>%
  ggplot(aes(x = PC1, y = PC2)) +
  geom_vline(xintercept = 0, linetype = 4) +
  geom_hline(yintercept = 0, linetype = 4) +
  geom_point(aes(color = category), size = 3, alpha = 0.8)  +
  scale_color_manual(values = c("black", "orange2", "grey70",
                               "orangered3", "orangered1", "seagreen", "dodgerblue2", "violetred2"), 
                    limits = c("genes", "TIR", "Gypsy", 
                               "ovary siren loci", "ovary siRNA loci", "seedling siRNA loci", "sperm siRNA loci", 
                               "zygote specific loci")) +
  labs(x = paste("PC1 (", pc_importance[1, 2] %>% signif(3)*100, "% of Variance)", sep = ""), 
       y = paste("PC2 (", pc_importance[2, 2] %>% signif(3)*100, "% of Variance)", "  ", sep = ""),
       fill = NULL,
       color = NULL) +  
  guides(fill = F) +
  theme_bw() +
  theme(text = element_text(size= 18, face="bold")) +
  theme(axis.text.x=element_text(colour = "black")) +
  theme(axis.text.y=element_text(colour = "black")) 
)

plot_grid(legend.source)
```

 
```{r}
plot_grid(a, NULL, legend.source,
          NULL, NULL, NULL,
          b, NULL, c, 
          nrow = 3, labels = c("A", "", "",
                               "", "", "", 
                               "B", "", "C"), label_size = 18,
          rel_widths = c(1, 0.1, 1),
          rel_heights = c(1, 0.1, 1)) 

ggsave("chip_dis.svg", height = 10, width = 10)
ggsave("chip_dis.png", height = 10, width = 10)
```


#boxplot 
x = category, y = medium, 
facet_wrap ~ tissue2 + type

 
```{r}
chip_s_keyed %>% 
  mutate(category = factor(category, levels = c(
    "genes", "TIR", "Gypsy", 
    "ovary siren loci", "ovary siRNA loci", "seedling siRNA loci", "sperm siRNA loci", 
    "zygote specific loci"
  ))) %>% 
  filter(str_detect(type, "DNase|input|preimm") == F) %>% 
  mutate(type_tissue2 = paste(type, tissue2, sep = "\n")) %>% 
  ggplot(aes(x = category)) +
  facet_wrap(~ type_tissue2) +
  geom_crossbar(aes(ymin = Q1 + 1, ymax = Q3 + 1, y = median + 1, fill = category), width = 0.7, alpha = 0.8) +
  geom_segment(aes(x = category, xend = category,  y = Q3 + 1, yend = UL + 1)) +
  geom_segment(aes(x = category, xend = category,  y = Q1 + 1, yend = LL + 1)) +
  geom_errorbar(aes(ymin = UL + 1, ymax = UL + 1), width = 0.3, size = 1) +
  geom_errorbar(aes(ymin = LL + 1, ymax = LL + 1), width = 0.3, size = 1) +
  scale_fill_manual(values = c("black", "orange2", "grey70",
                               "orangered3", "orangered1", "seagreen", "dodgerblue2"), 
                    limits = c("genes", "TIR", "Gypsy", 
                               "ovary siren loci", "ovary siRNA loci", "seedling siRNA loci", "sperm siRNA loci")) +
  scale_y_log10(breaks = c(1, 10, 100, 1000)) +
  scale_x_discrete(label = NULL) +
  labs(y = "RPKM",
       x = NULL,
       fill = NULL) +
  guides(fill = guide_legend(nrow = 2)) +
  theme_classic() +
  theme(legend.position = "bottom",
        strip.background = element_blank(),
        text = element_text(size = 18, color = "black"),
        axis.text = element_text(color = "black"),
        panel.spacing = unit(1, "lines") 
        ) 

ggsave("chip_box.svg", height = 12, width = 10)
ggsave("chip_box.png", height = 12, width = 10)
```

```{r}
chip_s_keyed %>% 
  mutate(category = factor(category, levels = c(
    "genes", "TIR", "Gypsy", 
    "ovary siren loci", "ovary siRNA loci", "seedling siRNA loci", "sperm siRNA loci", 
    "zygote specific loci"
  ))) %>% 
  filter(str_detect(type, "DNase")) %>% 
  mutate(type_tissue2 = paste(type, tissue2, sep = "\n")) %>% 
  ggplot(aes(x = category)) +
  facet_wrap(~ type_tissue2) +
  geom_crossbar(aes(ymin = Q1 + 1, ymax = Q3 + 1, y = median + 1, fill = category), width = 0.7, alpha = 0.8) +
  geom_segment(aes(x = category, xend = category,  y = Q3 + 1, yend = UL + 1)) +
  geom_segment(aes(x = category, xend = category,  y = Q1 + 1, yend = LL + 1)) +
  geom_errorbar(aes(ymin = UL + 1, ymax = UL + 1), width = 0.3, size = 1) +
  geom_errorbar(aes(ymin = LL + 1, ymax = LL + 1), width = 0.3, size = 1) +
  scale_fill_manual(values = c("black", "orange2", "grey70",
                               "orangered3", "orangered1", "seagreen", "dodgerblue2"), 
                    limits = c("genes", "TIR", "Gypsy", 
                               "ovary siren loci", "ovary siRNA loci", "seedling siRNA loci", "sperm siRNA loci")) +
  scale_y_log10(breaks = c(1, 10, 100, 1000)) +
  scale_x_discrete(label = NULL) +
  labs(y = "RPKM",
       x = NULL,
       fill = NULL) +
  guides(fill = guide_legend(nrow = 2)) +
  theme_classic() +
  theme(legend.position = "bottom",
        strip.background = element_blank(),
        text = element_text(size = 18, color = "black"),
        axis.text = element_text(color = "black"),
        panel.spacing = unit(1, "lines") 
        )  
```
```{r}
chip_s_keyed %>% 
  mutate(category = factor(category, levels = c(
    "genes", "TIR", "Gypsy", 
    "ovary siren loci", "ovary siRNA loci", "seedling siRNA loci", "sperm siRNA loci", 
    "zygote specific loci"
  ))) %>% 
  filter(str_detect(type, "input|preimm")) %>% 
  mutate(type_tissue2 = paste(type, tissue2, sep = "\n")) %>% 
  ggplot(aes(x = category)) +
  facet_wrap(~ type_tissue2) +
  geom_crossbar(aes(ymin = Q1 + 1, ymax = Q3 + 1, y = median + 1, fill = category), width = 0.7, alpha = 0.8) +
  geom_segment(aes(x = category, xend = category,  y = Q3 + 1, yend = UL + 1)) +
  geom_segment(aes(x = category, xend = category,  y = Q1 + 1, yend = LL + 1)) +
  geom_errorbar(aes(ymin = UL + 1, ymax = UL + 1), width = 0.3, size = 1) +
  geom_errorbar(aes(ymin = LL + 1, ymax = LL + 1), width = 0.3, size = 1) +
  scale_fill_manual(values = c("black", "orange2", "grey70",
                               "orangered3", "orangered1", "seagreen", "dodgerblue2"), 
                    limits = c("genes", "TIR", "Gypsy", 
                               "ovary siren loci", "ovary siRNA loci", "seedling siRNA loci", "sperm siRNA loci")) +
  scale_y_log10(breaks = c(1, 10, 100, 1000)) +
  scale_x_discrete(label = NULL) +
  labs(y = "RPKM",
       x = NULL,
       fill = NULL) +
  guides(fill = guide_legend(nrow = 2)) +
  theme_classic() +
  theme(legend.position = "bottom",
        strip.background = element_blank(),
        text = element_text(size = 18, color = "black"),
        axis.text = element_text(color = "black"),
        panel.spacing = unit(1, "lines") 
        )  
```


#linear models
##H3K9me2 
```{r}
model_chip_K9me2 <- lm(log10(RPKM + 1) ~ category, data = chip_keyed %>% 
                           filter(type == "H3K9me2"))
plot(model_chip_K9me2)
anova(model_chip_K9me2)
```
```{r}
est_k9me2 <- emmeans(model_chip_K9me2, pairwise ~ category)
multcomp::cld(est_k9me2$emmean, Letters = letters)
est_k9me2$contrast
```

```{r}
chip_s_keyed %>% 
  mutate(category = factor(category, levels = c(
    "genes", "TIR", "Gypsy", 
    "ovary siren loci", "ovary siRNA loci", "seedling siRNA loci", "sperm siRNA loci", 
    "zygote specific loci"
  ))) %>% 
  filter(str_detect(type, "H3K9me2")) %>% 
  mutate(type_tissue2 = paste(type, tissue2, sep = "\n")) %>% 
  ggplot(aes(x = category)) +
  facet_wrap(~ type_tissue2) +
  geom_crossbar(aes(ymin = Q1 + 1, ymax = Q3 + 1, y = median + 1, fill = category), width = 0.7, alpha = 0.8) +
  geom_segment(aes(x = category, xend = category,  y = Q3 + 1, yend = UL + 1)) +
  geom_segment(aes(x = category, xend = category,  y = Q1 + 1, yend = LL + 1)) +
  geom_errorbar(aes(ymin = UL + 1, ymax = UL + 1), width = 0.3, size = 1) +
  geom_errorbar(aes(ymin = LL + 1, ymax = LL + 1), width = 0.3, size = 1) +
  scale_fill_manual(values = c("black", "orange2", "grey70",
                               "orangered3", "orangered1", "seagreen", "dodgerblue2"), 
                    limits = c("genes", "TIR", "Gypsy", 
                               "ovary siren loci", "ovary siRNA loci", "seedling siRNA loci", "sperm siRNA loci")) +
  scale_y_log10(breaks = c(1, 10, 100, 1000)) +
  scale_x_discrete(label = NULL) +
  labs(y = "RPKM",
       x = NULL,
       fill = NULL) +
  guides(fill = guide_legend(nrow = 4)) +
  theme_classic() +
  theme(legend.position = "bottom",
        strip.background = element_blank(),
        text = element_text(size = 18, color = "black"),
        axis.text = element_text(color = "black"),
        panel.spacing = unit(1, "lines") 
        ) 

ggsave("H3K9me2.svg", height = 5, width = 5)
ggsave("H3K9me2.png", height = 5, width = 5)
```


##H3K9ac
```{r}
model_chip_H3K4me2 <- lm(log10(RPKM + 1) ~ category, data = chip_keyed %>% 
                           filter(str_detect(type, "H3K4me2")))
plot(model_chip_H3K4me2)
anova(model_chip_H3K4me2)
```

```{r}
est_k4 <- emmeans(model_chip_H3K4me2, pairwise ~ category)
multcomp::cld(est_k4$emmean, Letters = letters)
est_k4$contrast
```

```{r}
chip_s_keyed %>% 
  mutate(category = factor(category, levels = c(
    "genes", "TIR", "Gypsy", 
    "ovary siren loci", "ovary siRNA loci", "seedling siRNA loci", "sperm siRNA loci", 
    "zygote specific loci"
  ))) %>% 
  filter(str_detect(type, "H3K4me2")) %>% 
  mutate(type_tissue2 = paste(type, tissue2, sep = "\n")) %>% 
  ggplot(aes(x = category)) +
  facet_wrap(~ type_tissue2) +
  geom_crossbar(aes(ymin = Q1 + 1, ymax = Q3 + 1, y = median + 1, fill = category), width = 0.7, alpha = 0.8) +
  geom_segment(aes(x = category, xend = category,  y = Q3 + 1, yend = UL + 1)) +
  geom_segment(aes(x = category, xend = category,  y = Q1 + 1, yend = LL + 1)) +
  geom_errorbar(aes(ymin = UL + 1, ymax = UL + 1), width = 0.3, size = 1) +
  geom_errorbar(aes(ymin = LL + 1, ymax = LL + 1), width = 0.3, size = 1) +
  scale_fill_manual(values = c("black", "orange2", "grey70",
                               "orangered3", "orangered1", "seagreen", "dodgerblue2"), 
                    limits = c("genes", "TIR", "Gypsy", 
                               "ovary siren loci", "ovary siRNA loci", "seedling siRNA loci", "sperm siRNA loci")) +
  scale_y_log10(breaks = c(1, 10, 100, 1000)) +
  scale_x_discrete(label = NULL) +
  labs(y = "RPKM",
       x = NULL,
       fill = NULL) +
  guides(fill = guide_legend(nrow = 4)) +
  theme_classic() +
  theme(legend.position = "bottom",
        strip.background = element_blank(),
        text = element_text(size = 18, color = "black"),
        axis.text = element_text(color = "black"),
        panel.spacing = unit(1, "lines") 
        ) 

ggsave("H3K9ac.svg", height = 5, width = 5)
ggsave("H3K9ac.png", height = 5, width = 5)
```


































