---
title: "Zygote_de_novo_siRNA_metagene"
author: "Chenxin Li"
date: "3/14/2020"
output:  
  html_notebook:
    number_sections: yes
    toc: yes
    toc_float: yes
  html_document:
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(emmeans)
library(tidyr)
library(dplyr)
library(readr)
library(readxl)
library(RColorBrewer)
library(viridis)
library(stringr)
library(svglite)
library(cowplot)
```


#data
```{r}
meta_list <-  list.files(path = "C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/CLVS12/loci_metagenes/zec", pattern = "*.txt", full.names = T)

meta_list2 <-  list.files(path = "C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/CLVS12/loci_metagenes/zec_name_changed", pattern = "*.txt", full.names = T)

head(meta_list)
head(meta_list2)

metagenes  <- sapply(meta_list2, read_delim, simplify = FALSE,  delim = "\t") %>% 
  bind_rows(.id = "id")

temp <- metagenes %>% 
  group_by(id) %>%
  count()

temp
```
```{r}
str_length("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/CLVS12/loci_metagenes/zec/")
```


```{r}
file_names <- data.frame(
  name = meta_list %>% as.vector(),
  index = 1:length(meta_list)
)

head(file_names)

metagenes_clean <- metagenes %>% 
  mutate(index1 = str_extract(id, "\\(\\d\\)|\\(\\d\\d\\)|\\(\\d\\d\\d\\)")) %>% 
  mutate(index2 = str_remove(index1, "\\(")) %>% 
  mutate(index = str_remove(index2, "\\)")) %>% 
  mutate(index = as.numeric(index)) %>% 
  arrange(index) %>% 
  inner_join(file_names, by = "index") %>% 
  mutate(name.short = str_sub(name, 90, 110))

metagenes_clean %>% head(10)
```
```{r}
sample_des <- read_excel("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/CLVS12/sample_des_clvs12.xlsx")

smRNA_comp <- read_csv("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/CLVS12/codes_and_output/smRNA_comp.csv")

total_siRNA_length1 <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/CLVS_smRNA_revision/length_profiel_fig2/lengths_summary.bam.siRNAs.sam.txt", 
    "\t", escape_double = FALSE, trim_ws = TRUE)

CLVS12_total <-  read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/CLVS12/zygote_siRNAs/length_counts/lengths_summary.siRNAs.sam.txt", 
    "\t", escape_double = FALSE, trim_ws = TRUE)
```

```{r}
total_siRNA_length <- total_siRNA_length1 %>%
  rbind(CLVS12_total %>% 
          filter(str_detect(X1, "q20") == F))
```


#arrange
```{r}
identify_samples <- function(df){
  df %>% 
    mutate(sample_ID = case_when(
    str_detect(library, "sperm.1") ~ "BS1", #1
    str_detect(library, "Sperm2") ~ "BS2",  #2
    str_detect(library, "Sperm4a") ~ "BS4a",  #3
    str_detect(library, "sperm4b") ~ "BS4b",  #4
    str_detect(library, "sperm6a") ~ "BS6a",  #5
    str_detect(library, "sperm6b") ~ "BS6b",  #6
    str_detect(library, "sperm.5b") ~ "SP5b", #7
    str_detect(library, "sperm.5c") ~ "SP5c", #8
    str_detect(library, "Bulk.15") ~ "B15",   #9
    str_detect(library, "Bulk.20") ~ "B20",   #10
    str_detect(library, "Bulk.25") ~ "B25",   #11
    str_detect(library, "seedling4") ~ "SD4", #12
    str_detect(library, "egg.9a") ~ "E9a",    #13
    str_detect(library, "egg.9b") ~ "E9b",    #14
    str_detect(library, "egg.9c") ~ "E9c",    #15
    str_detect(library, "eggcell4") ~ "E4",   #16
    str_detect(library, "eggcell3") ~ "E3",   #17
    str_detect(library, "eggcell2") ~ "E2",   #18
    str_detect(library, "ovary.no.egg.1a") ~ "OV1a",    #19
    str_detect(library, "ovary.no.egg.1b") ~ "OV1b",    #20
    str_detect(library, "Ovarynoegg2") ~ "OV2",         #21
    str_detect(library, "SRR57") ~ "root",              #22
    str_detect(library, "ab_control") ~ "ddm1_con",     #23
    str_detect(library, "ddm1ab") ~ "ddm1",             #24
    str_detect(library, "drm2-T-DNA_control") ~ "drm2_con",  #25 drm2-T-DNA_control.fastq
    str_detect(library, "drm2-T-DNA.fas") ~ "drm2",          #26   
    str_detect(library, "SRR2544786") ~ "em_dry", #27  
    str_detect(library, "SRR5049778") ~ "an_pre",  #28
    str_detect(library, "SRR5049779") ~ "an_mei",  #29
    str_detect(library, "SRR5049780") ~ "an_mic",  #30
    str_detect(library, "SRR5049781") ~ "an_bi",   #31
    str_detect(library, "SRR5049786") ~ "ov_1st",  #32
    str_detect(library, "SRR5049787") ~ "ov_2nd",  #33
    str_detect(library, "SRR5049788") ~ "ov_3rd",  #34
    str_detect(library, "SRR5049789") ~ "ov_4th",  #35
    str_detect(library, "S3_1") ~ "S3_1",          #36
    str_detect(library, "S3_2") ~ "S3_2",          #37
    str_detect(library, "S3_3") ~ "S3_3",          #38
    str_detect(library, "S5_1") ~ "S5_1",          #39
    str_detect(library, "S5_2") ~ "S5_2",          #40
    str_detect(library, "S5_3") ~ "S5_3",          #41
    str_detect(library, "S7_1") ~ "S7_1",          #42
    str_detect(library, "S7_2") ~ "S7_2",          #43
    str_detect(library, "S7_3") ~ "S7_3",          #44
    str_detect(library, "SRR2544787") ~ "em_12h",  #45
    str_detect(library, "SRR2544788") ~ "em_24h",  #46
    str_detect(library, "SRR771501") ~ "em_7DAF",  #47
    str_detect(library, "SRR771500") ~ "en_7DAF",   #48
    str_detect(library, "SD7") ~ "SD7", #49
    str_detect(library, "zg1d") ~ "zg1d", #50
    str_detect(library, "zg1e") ~ "zg1e",  #51
    str_detect(library, "zg2d") ~ "zg2d",  #52
    str_detect(library, "zg2e") ~ "zg2e",  #53
    str_detect(library, "zg3a") ~ "zg3a", #54
    str_detect(library, "zg3b") ~ "zg3b"  #55
  )) 
}
```

```{r}
total_siRNA_length <- total_siRNA_length %>% 
  mutate(library = X1) %>% 
  identify_samples()


sample_des_size <- smRNA_comp %>% 
  inner_join(sample_des, by = "sample_ID") %>% 
  select(-library) %>% 
  inner_join(total_siRNA_length, by = "sample_ID")

sample_des_size %>% head()
```

```{r}
metagenes_clean_clean <- metagenes_clean %>% 
  mutate(library = name) %>% 
  identify_samples() %>% 
  mutate(location = case_when(
    str_detect(name, "upstream") ~ "5' end",
    str_detect(name, "downstream") ~ "3' end"
  )) %>% 
  mutate(location = factor(location, levels = c(
    "5' end", "3' end"
  ))) %>%
  inner_join(sample_des_size, by = "sample_ID") %>% 
  mutate(pro_24 = `total overlap`/ `24`) %>% 
  mutate(pro_sm = `total overlap`/ `total read`) %>% 
  mutate(pro_si = `total overlap`/ `general siRNA`) 

head(metagenes_clean_clean)
```

#zygote, embryo 8DAF, seedling 
```{r}
metagenes_clean_clean %>% 
  filter(sample_type == "egg"|
           sample_type == "sperm"|
           sample_type == "seedling shoot"|
           sample_type == "zygote"|
           str_detect(sample_type, "DAF")) %>%
  filter(str_detect(sample_type, "endo") == F) %>%
  mutate(sample_type = case_when(
    str_detect(sample_type, "embryo") ~ "embryo",
    str_detect(sample_type, "seedling") ~ "seedling",
    T ~ sample_type
  )) %>% 
  ggplot(aes(x = `bin start`, y = pro_24 * 1000)) +
  facet_grid(.~location, scales = "free_x")+
  stat_summary(geom = "ribbon",  fun.data = "mean_cl_boot", aes(fill = sample_type), alpha = 0.3) +
  stat_summary(geom = "line", fun.y = mean, aes(group = sample_type, color = sample_type), size = 1.25, alpha = 0.8) +
  scale_x_continuous(breaks = c(-3000,-2000,-1000, 0, 1000, 2000, 2900),
                     labels = NULL)+
  scale_color_manual(values = c("tomato1", "seagreen", "dodgerblue2", "violetred2", "grey20"),
                    limits = c("egg", "seedling", "sperm", "zygote", "embryo")) +
  scale_fill_manual(values = c("tomato1", "seagreen", "dodgerblue2", "violetred2", "grey20"),
                    limits = c("egg", "seedling", "sperm", "zygote", "embryo")) +
  scale_y_continuous(breaks = c(0, 50, 100)) +
  guides(fill = F) + 
  labs(color = NULL,
       x = NULL, 
       y = "24-nt siRNA coverage") + 
  theme_minimal()+
  theme(legend.position = c(0.75, 0.8)) +
  theme(axis.line = element_line(size = 1.2)) +
  theme(text = element_text(size = 18, face="bold")) +
  theme(axis.text.x=element_text(colour="black")) +
  theme(axis.text.y=element_text(colour="black"))

ggsave(filename = "24_meta_gamate.svg", height = 4, width = 4.7)
ggsave(filename = "24_meta_gamate.png", height = 4, width = 4.7)
```







Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.